/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_MatrixInterface */

#ifndef _Included_com_MatrixInterface
#define _Included_com_MatrixInterface
#ifdef __cplusplus
extern "C" {
#endif
#undef com_MatrixInterface_SUCCESS
#define com_MatrixInterface_SUCCESS 1i64
/*
 * Class:     com_MatrixInterface
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_MatrixInterface_test
  (JNIEnv *, jobject);

/*
 * Class:     com_MatrixInterface
 * Method:    init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_MatrixInterface_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_MatrixInterface
 * Method:    rundown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_MatrixInterface_rundown
  (JNIEnv *, jobject);

/*
 * Class:     com_MatrixInterface
 * Method:    getStringProperty
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_MatrixInterface_getStringProperty
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_MatrixInterface
 * Method:    getDoubleProperty
 * Signature: (Ljava/lang/String;I)D
 */
JNIEXPORT jdouble JNICALL Java_com_MatrixInterface_getDoubleProperty
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_MatrixInterface
 * Method:    getIntegerProperty
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_MatrixInterface_getIntegerProperty
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_MatrixInterface
 * Method:    getEnumProperty
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_MatrixInterface_getEnumProperty
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_MatrixInterface
 * Method:    getPairProperty
 * Signature: (Ljava/lang/String;I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_MatrixInterface_getPairProperty
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_MatrixInterface
 * Method:    getDoubleArrayProperty
 * Signature: (Ljava/lang/String;I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_MatrixInterface_getDoubleArrayProperty
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_MatrixInterface
 * Method:    getBooleanProperty
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_MatrixInterface_getBooleanProperty
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_MatrixInterface
 * Method:    setStringProperty
 * Signature: (Ljava/lang/String;ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_MatrixInterface_setStringProperty
  (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     com_MatrixInterface
 * Method:    setDoubleProperty
 * Signature: (Ljava/lang/String;ID)J
 */
JNIEXPORT jlong JNICALL Java_com_MatrixInterface_setDoubleProperty
  (JNIEnv *, jobject, jstring, jint, jdouble);

/*
 * Class:     com_MatrixInterface
 * Method:    setIntegerProperty
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_com_MatrixInterface_setIntegerProperty
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_MatrixInterface
 * Method:    setBooleanProperty
 * Signature: (Ljava/lang/String;IZ)J
 */
JNIEXPORT jlong JNICALL Java_com_MatrixInterface_setBooleanProperty
  (JNIEnv *, jobject, jstring, jint, jboolean);

/*
 * Class:     com_MatrixInterface
 * Method:    setEnumProperty
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_com_MatrixInterface_setEnumProperty
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_MatrixInterface
 * Method:    setPairProperty
 * Signature: (Ljava/lang/String;IDD)J
 */
JNIEXPORT jlong JNICALL Java_com_MatrixInterface_setPairProperty
  (JNIEnv *, jobject, jstring, jint, jdouble, jdouble);

/*
 * Class:     com_MatrixInterface
 * Method:    callVoidFunction
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_MatrixInterface_callVoidFunction
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_MatrixInterface
 * Method:    callDoubleReturnFunction
 * Signature: (Ljava/lang/String;Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_com_MatrixInterface_callDoubleReturnFunction
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_MatrixInterface
 * Method:    setTrigger1
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_MatrixInterface_setTrigger1
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_MatrixInterface
 * Method:    setTrigger2
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_MatrixInterface_setTrigger2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_MatrixInterface
 * Method:    setTrigger3
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_MatrixInterface_setTrigger3
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_MatrixInterface
 * Method:    setTrigger4
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_MatrixInterface_setTrigger4
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_MatrixInterface
 * Method:    setArrayObserver1
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_MatrixInterface_setArrayObserver1
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
